# Esercitazione

Importa le diverse librerie

In [ ]:
import random
import re
from collections import Counter, defaultdict
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Preparazione dati e analisi del testo

Importa i dati da un archivio
dei contenuti di Wikipedia e messo a disposizione sulla piattaforma
[Hugging Face](https://huggingface.co/datasets/Salesforce/wikitext) (Merity et al., 2016).

In [ ]:
from datasets import load_dataset

dataset = load_dataset("wikitext", "wikitext-103-raw-v1")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

wikitext-103-raw-v1/test-00000-of-00001.(…):   0%|          | 0.00/733k [00:00<?, ?B/s]

wikitext-103-raw-v1/train-00000-of-00002(…):   0%|          | 0.00/157M [00:00<?, ?B/s]

wikitext-103-raw-v1/train-00001-of-00002(…):   0%|          | 0.00/157M [00:00<?, ?B/s]

wikitext-103-raw-v1/validation-00000-of-(…):   0%|          | 0.00/657k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/1801350 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]

Utilizza prima solo i dati del dataset *test*. In un secondo momento puoi ripetere l'esercitazione con il dataset *train*, cambiando il nome tra parentesi quadre.

In [ ]:
data = dataset["test"]
testo = " ".join(data["text"])
print("Lunghezza testo:", len(testo))

Lunghezza testo: 1289979

### Tokenizzazione

Crea una lista delle parole presenti.

In [ ]:
tokens = re.findall(r"\b\w+\b", testo.lower())
tokens[:10]

['robert',
 'boulter',
 'robert',
 'boulter',
 'is',
 'an',
 'english',
 'film',
 'television',
 'and']

## Modello di ordine 0


### Training

Cosa apprende il modello? Nella fase di training calcola le frequenza di ogni **parola tipo** presente nel testo. Il dataframe *df* creato contiene le informazioni apprese da nostro semplice modello di liguaggio naturale.

In [ ]:
tokens = re.findall(r"\b\w+\b", testo.lower())
l_corpus= len(tokens)
frequenze_type = Counter(tokens)

df = (
    pd.DataFrame(frequenze_type.items(), columns=["type", "frequenza"])
    .sort_values(by="frequenza", ascending=False)
    .reset_index(drop=True)
)
df["probabilità"] = df.frequenza/l_corpus
df.head()

  type  frequenza  probabilità
0  the      16083     0.077891
1   of       6789     0.032880
2  and       5885     0.028502
3   in       5079     0.024598
4   to       4787     0.023184

### Predict

Dopo la fase di apprendimento puoi passare a fare la previsione. In questo caso il modello ti restituisce semplicemente la parola più probabile.

In [ ]:
def predictM0(df):
  parola_successiva = df.loc[df["probabilità"].idxmax(), "type"]
  return ("La parola prevista è:", parola_successiva)

In [ ]:
predictM0(df)

('La parola prevista è:', 'the')

### Osservazioni

Cosa non considera un modello di ordine 0?

Inserisci qui le tue risposte

## Modello di ordine 1

Considera ora la probabilità di ogni bigramma e non più della singola parola type.

### Training

Costruisci i bigrammi cioè le coppie di parole

In [ ]:
bigrammi = list(zip(tokens[:-1], tokens[1:]))
print(bigrammi[1:10])

[('boulter', 'robert'), ('robert', 'boulter'), ('boulter', 'is'), ('is', 'an'), ('an', 'english'), ('english', 'film'), ('film', 'television'), ('television', 'and'), ('and', 'theatre')]

Calcola la frequenza di ogni bigramma tipo, quindi dell'evento intersezione.

In [ ]:
frequenze_bigrammi = Counter(bigrammi)
print(frequenze_bigrammi)

Counter({('of', 'the'): 2187, ('in', 'the'): 1390, ('to', 'the'): 811, ('and', 'the'): 558, ('on', 'the'): 522, ('for', 'the'): 429, ('at', 'the'): 388, ('by', 'the'): 351, ('from', 'the'): 345, ('with', 'the'): 345, ('as', 'a'): 305, ('the', 'first'): 305, ('as', 'the'): 302, ('to', 'be'): 264, ('of', 'a'): 249, ('in', 'a'): 241, ('it', 'was'): 236, ('that', 'the'): 232, ('he', 'was'): 231, ('during', 'the'): 198, ('with', 'a'): 184, ('was', 'the'): 173, ('was', 'a'): 149, ('and', 'a'): 148, ('to', 'a'): 147, ('the', 'city'): 145, ('one', 'of'): 140, ('of', 'his'): 136, ('the', 'film'): 136, ('had', 'been'): 118, ('have', 'been'): 117, ('is', 'a'): 115, ('it', 'is'): 112, ('km', 'h'): 111, ('the', 'north'): 110, ('is', 'the'): 109, ('due', 'to'): 106, ('and', 'was'): 106, ('after', 'the'): 106, ('the', 'second'): 103, ('the', 'british'): 101, ('number', 'of'): 100, ('for', 'a'): 99, ('that', 'he'): 99, ('the', 'united'): 99, ('such', 'as'): 98, ('the', 'philippines'): 98, ('he', 'had'): 97, ('into', 'the'): 97, ('the', 'french'): 97, ('in', 'his'): 96, ('did', 'not'): 96, ('the', 'most'): 94, ('the', 'us'): 93, ('part', 'of'): 92, ('on', 'a'): 91, ('the', 'same'): 89, ('the', 'war'): 88, ('end', 'of'): 84, ('they', 'were'): 82, ('the', 'storm'): 82, ('by', 'a'): 81, ('has', 'been'): 81, ('united', 'states'): 80, ('north', 'korean'): 80, ('the', 'end'): 79, ('the', 'new'): 78, ('out', 'of'): 75, ('through', 'the'): 72, ('american', 'beauty'): 72, ('world', 'war'): 71, ('tropical', 'storm'): 71, ('the', 'world'): 71, ('to', 'have'): 70, ('the', 'album'): 70, ('the', 'game'): 70, ('du', 'fu'): 69, ('known', 'as'): 69, ('the', 'time'): 68, ('the', 'next'): 68, ('the', 'year'): 68, ('according', 'to'): 67, ('would', 'be'): 67, ('along', 'the'): 67, ('most', 'of'): 66, ('the', 'following'): 66, ('which', 'was'): 65, ('the', 'national'): 65, ('the', 'head'): 65, ('the', 'river'): 65, ('the', 'commission'): 65, ('had', 'a'): 64, ('against', 'the'): 64, ('the', 'battle'): 64, ('battle', 'of'): 63, ('was', 'also'): 62, ('a', 'number'): 62, ('the', 'embassy'): 62, ('nero', 's'): 62, ('over', 'the'): 61, ('north', 'koreans'): 60, ('when', 'the'): 59, ('under', 'the'): 59, ('the', 'town'): 59, ('within', 'the'): 59, ('a', 'few'): 58, ('new', 'york'): 58, ('was', 'not'): 57, ('into', 'a'): 57, ('as', 'well'): 57, ('san', 'lorenzo'): 57, ('ny', '93'): 57, ('the', 'two'): 56, ('on', 'september'): 56, ('and', 'his'): 55, ('as', 'an'): 55, ('and', 'in'): 54, ('is', 'also'): 54, ('at', 'a'): 54, ('while', 'the'): 53, ('that', 'it'): 53, ('the', 'early'): 53, ('the', 'group'): 53, ('from', 'a'): 53, ('a', 'new'): 53, ('the', 'jma'): 53, ('the', 'doctor'): 53, ('the', 'american'): 52, ('a', 'tropical'): 52, ('tropical', 'depression'): 52, ('was', 'to'): 49, ('in', 'which'): 49, ('on', 'october'): 49, ('he', 'is'): 48, ('the', 'other'): 48, ('between', 'the'): 48, ('to', 'his'): 47, ('at', 'least'): 47, ('the', 'south'): 47, ('who', 'had'): 46, ('more', 'than'): 46, ('the', 'only'): 46, ('well', 'as'): 46, ('on', 'august'): 46, ('and', 'that'): 45, ('when', 'he'): 45, ('continued', 'to'): 45, ('that', 'they'): 45, ('lester', 's'): 45, ('would', 'have'): 44, ('in', 'an'): 44, ('of', 'manila'): 44, ('because', 'of'): 43, ('for', 'his'): 43, ('some', 'of'): 43, ('off', 'the'): 43, ('led', 'to'): 43, ('of', 'their'): 43, ('on', 'june'): 43, ('he', 'also'): 42, ('became', 'the'): 42, ('use', 'of'): 42, ('in', 'this'): 42, ('the', 'season'): 42, ('winds', 'of'): 42, ('across', 'the'): 42, ('on', 'july'): 42, ('this', 'was'): 41, ('to', 'make'): 41, ('of', 'an'): 41, ('able', 'to'): 41, ('had', 'to'): 41, ('the', 'third'): 41, ('the', '1st'): 41, ('but', 'the'): 41, ('as', 'it'): 41, ('the', 'naktong'): 41, ('around', 'the'): 41, ('which', 'he'): 40, ('since', 'the'): 40, ('in', 'their'): 40, ('there', 'were'): 40, ('the', 'band'): 40, ('the', 'division'): 40, ('the', 'country'): 40, ('there', 'are'): 39, ('him', 'to'): 39, ('until', 'the'): 39, ('the', 'japanese'): 39, ('the', 'final'): 39, ('the', 'latter'): 39, ('east', 'of'): 39, ('area', 'of'): 39, ('they', 'are'): 39, ('colossal', 'head'): 39, ('the', 'royal'): 38, ('back', 'to'): 38, ('in', 'addition'): 38, ('for', 'its'): 38, ('of', 'which'): 38, ('a', 'result'): 38, ('of', 'these'): 38, ('the', 'top'): 38, ('the', 'university'): 38, ('the', 'match'): 38, ('who', 'was'): 37, ('based', 'on'): 37, ('which', 'is'): 37, ('university', 'of'): 37, ('a', 'large'): 37, ('the', 'german'): 37, ('of', 'nero'): 37, ('rather', 'than'): 36, ('of', 'this'): 36, ('may', 'have'): 36, ('moved', 'to'): 36, ('among', 'the'): 36, ('was', 'released'): 36, ('before', 'the'): 36, ('on', 'may'): 36, ('the', 'senate'): 36, ('and', 'he'): 35, ('many', 'of'): 35, ('his', 'own'): 35, ('where', 'he'): 35, ('with', 'his'): 35, ('day', 'the'): 35, ('there', 'was'): 35, ('in', 'its'): 35, ('of', 'its'): 35, ('the', 'great'): 35, ('the', 'main'): 35, ('up', 'to'): 35, ('return', 'to'): 35, ('his', 'first'): 35, ('won', 'the'): 35, ('the', 'east'): 35, ('near', 'the'): 35, ('the', 'best'): 35, ('members', 'of'): 35, ('responsible', 'for'): 35, ('the', 'system'): 35, ('the', 'jtwc'): 35, ('and', 'had'): 34, ('this', 'time'): 34, ('began', 'to'): 34, ('the', 'area'): 34, ('and', 'other'): 34, ('and', 'is'): 34, ('war', 'ii'): 34, ('all', 'of'): 34, ('to', 'tropical'): 34, ('the', 'typhoon'): 34, ('and', 'on'): 33, ('following', 'the'): 33, ('a', 'single'): 33, ('the', 'ships'): 33, ('and', 'to'): 33, ('the', '2nd'): 33, ('2nd', 'division'): 33, ('throughout', 'the'): 33, ('to', 'take'): 33, ('has', 'a'): 33, ('the', 'headdress'): 33, ('is', 'an'): 32, ('was', 'in'): 32, ('returned', 'to'): 32, ('be', 'a'): 32, ('the', 'state'): 32, ('said', 'that'): 32, ('where', 'the'): 32, ('the', 'night'): 32, ('high', 'school'): 32, ('after', 'a'): 32, ('the', 'philippine'): 32, ('could', 'be'): 31, ('than', 'the'): 31, ('the', 'rest'): 31, ('as', 'part'): 31, ('were', 'also'): 31, ('side', 'of'): 31, ('which', 'the'): 31, ('be', 'the'): 31, ('tropical', 'cyclone'): 31, ('on', 'november'): 31, ('from', 'his'): 30, ('time', 'the'): 30, ('all', 'the'): 30, ('series', 'of'): 30, ('about', 'the'): 30, ('the', 'week'): 30, ('front', 'of'): 30, ('the', 'last'): 30, ('they', 'had'): 30, ('were', 'not'): 30, ('that', 'were'): 30, ('to', 'an'): 30, ('the', 'largest'): 30, ('are', 'the'): 30, ('lesnar', 's'): 30, ('the', 'bintulu'): 30, ('in', 'bintulu'): 30, ('along', 'with'): 29, ('unable', 'to'): 29, ('fu', 's'): 29, ('and', 'two'): 29, ('the', 'western'): 29, ('to', 'become'): 29, ('lack', 'of'): 29, ('and', 'their'): 29, ('she', 'was'): 29, ('was', 'named'): 29, ('the', 'team'): 29, ('north', 'of'): 29, ('a', 'company'): 29, ('next', 'day'): 29, ('although', 'the'): 29, ('on', 'april'): 29, ('the', 'tetrarch'): 29, ('manila', 'is'): 29, ('that', 'of'): 28, ('in', 'june'): 28, ('can', 'be'): 28, ('a', 'small'): 28, ('intended', 'to'): 28, ('the', 'middle'): 28, ('that', 'was'): 28, ('also', 'the'): 28, ('west', 'of'): 28, ('placed', 'in'): 28, ('civil', 'war'): 28, ('the', 'work'): 28, ('in', 'may'): 27, ('rest', 'of'): 27, ('the', 'song'): 27, ('the', 'late'): 27, ('and', 'it'): 27, ('the', 'road'): 27, ('used', 'to'): 27, ('in', 'july'): 27, ('could', 'not'): 27, ('a', 'total'): 27, ('the', 'face'): 27, ('that', 'is'): 27, ('the', 'west'): 27, ('including', 'the'): 27, ('9th', 'infantry'): 27, ('colossal', 'heads'): 27, ('but', 'he'): 26, ('he', 'has'): 26, ('and', 'one'): 26, ('a', 'more'): 26, ('in', 'march'): 26, ('united', 'kingdom'): 26, ('both', 'the'): 26, ('music', 'video'): 26, ('it', 's'): 26, ('the', 'number'): 26, ('result', 'of'): 26, ('to', 'their'): 26, ('los', 'angeles'): 26, ('in', 'early'): 26, ('with', 'an'): 26, ('command', 'of'): 26, ('is', 'not'): 26, ('became', 'a'): 26, ('history', 'of'): 26, ('it', 'the'): 26, ('the', 'center'): 26, ('also', 'known'): 26, ('south', 'of'): 26, ('stated', 'that'): 26, ('the', 'image'): 26, ('member', 'of'): 26, ('to', 'win'): 26, ('as', 'of'): 26, ('is', 'located'): 26, ('war', 'office'): 26, ('the', 'monument'): 26, ('free', 'derry'): 26, ('transferred', 'to'): 25, ('found', 'in'): 25, ('it', 'to'): 25, ('development', 'of'): 25, ('resulted', 'in'): 25, ('the', 'front'): 25, ('the', 'nk'): 25, ('the', 'line'): 25, ('the', 'company'): 25, ('to', 'its'): 25, ('the', 'back'): 25, ('tropical', 'cyclones'): 25, ('view', 'of'): 25, ('the', 'depression'): 25, ('british', 'army'): 25, ('the', 'olmec'): 25, ('the', 'bogside'): 25, ('as', 'one'): 24, ('city', 'of'): 24, ('however', 'the'): 24, ('away', 'from'): 24, ('but', 'was'): 24, ('and', 'its'): 24, ('city', 's'): 24, ('royal', 'navy'): 24, ('had', 'the'): 24, ('replaced', 'by'): 24, ('the', 'former'): 24, ('that', 'a'): 24, ('infantry', 'division'): 24, ('much', 'of'): 24, ('and', 'later'): 24, ('it', 'as'): 24, ('the', 'way'): 24, ('the', 'tank'): 24, ('on', 'january'): 24, ('u', 's'): 24, ('the', 'book'): 24, ('may', 'be'): 24, ('for', 'best'): 24, ('the', 'name'): 24, ('an', 'area'): 24, ('the', 'wwe'): 24, ('the', 'script'): 24, ('the', 'squadron'): 24, ('episode', 'of'): 23, ('a', 'series'): 23, ('order', 'to'): 23, ('in', 'september'): 23, ('addition', 'to'): 23, ('as', 'his'): 23, ('on', 'his'): 23, ('which', 'had'): 23, ('which', 'were'): 23, ('was', 'found'): 23, ('the', 'original'): 23, ('at', 'number'): 23, ('on', 'its'): 23, ('ships', 'were'): 23, ('were', 'the'): 23, ('that', 'had'): 23, ('and', 'were'): 23, ('during', 'his'): 23, ('the', 'fourth'): 23, ('the', 'day'): 23, ('win', 'the'): 23, ('1st', 'battalion'): 23, ('the', 'title'): 23, ('the', 'austrian'): 23, ('associated', 'with'): 23, ('his', 'career'): 23, ('in', 'january'): 23, ('ambassador', 'bishop'): 23, ('lesnar', 'was'): 23, ('the', 'snowmen'): 23, ('la', 'venta'): 23, ('stone', 'sour'): 23, ('type', 'ub'): 23, ('directed', 'by'): 22, ('in', 'november'): 22, ('called', 'the'): 22, ('by', 'his'): 22, ('first', 'time'): 22, ('after', 'his'): 22, ('the', 'right'): 22, ('attempted', 'to'): 22, ('down', 'the'): 22, ('this', 'is'): 22, ('as', 'he'): 22, ('in', 'april'): 22, ('long', 'tons'): 22, ('total', 'of'): 22, ('and', 'then'): 22, ('decided', 'to'): 22, ('days', 'later'): 22, ('of', 'them'): 22, ('half', 'of'): 22, ('made', 'his'): 22, ('us', '2nd'): 22, ('later', 'in'): 22, ('he', 'said'): 22, ('towards', 'the'): 22, ('the', 'ironclad'): 22, ('there', 'is'): 22, ('s', 'death'): 22, ('that', 'are'): 22, ('town', 'of'): 22, ('manchester', 'united'): 22, ('national', 'league'): 22, ('bacon', 's'): 22, ('the', 'danube'): 22, ('heavyweight', 'champion'): 22, ('the', 'rock'): 22, ('f', '5'): 22, ('col', 'fitts'): 22, ('sm', 'ub'): 22, ('followed', 'by'): 21, ('the', 'episode'): 21, ('made', 'a'): 21, ('up', 'the'): 21, ('in', 'order'): 21, ('and', 'by'): 21, ('began', 'in'): 21, ('him', 'the'): 21, ('of', 'all'): 21, ('the', 'northern'): 21, ('for', 'their'): 21, ('in', 'late'): 21, ('and', 'at'): 21, ('that', 'day'): 21, ('to', 'play'): 21, ('making', 'it'): 21, ('close', 'to'): 21, ('outside', 'the'): 21, ('he', 'would'): 21, ('would', 'not'): 21, ('the', 'northeast'): 21, ('heavyweight', 'championship'): 21, ('the', 'scene'): 21, ('the', 'studio'): 21, ('head', 'was'): 21, ('museum', 'of'): 21, ('film', 's'): 21, ('role', 'in'): 20, ('appeared', 'in'): 20, ('the', 'production'): 20, ('war', 'the'): 20, ('to', 'join'): 20, ('to', 'do'): 20, ('the', 'central'): 20, ('which', 'are'): 20, ('kiss', 'you'): 20, ('peaked', 'at'): 20, ('to', 'get'): 20, ('construction', 'of'): 20, ('and', 'an'): 20, ('that', 'time'): 20, ('the', 'fire'): 20, ('it', 'has'): 20, ('per', 'hour'): 20, ('the', 'local'): 20, ('the', 'four'): 20, ('the', 'base'): 20, ('on', 'to'): 20, ('edge', 'of'): 20, ('air', 'force'): 20, ('the', 'entire'): 20, ('the', 'army'): 20, ('the', 'use'): 20, ('the', 'italian'): 20, ('form', 'of'): 20, ('the', 'skull'): 20, ('the', 'case'): 20, ('prior', 'to'): 20, ('the', 'evacuees'): 20, ('wind', 'shear'): 20, ('by', '1'): 20, ('tres', 'zapotes'): 20, ('nero', 'was'): 20, ('the', 'roman'): 20, ('beth', 'israel'): 20, ('don', 't'): 19, ('like', 'the'): 19, ('came', 'to'): 19, ('in', 'both'): 19, ('the', 'poem'): 19, ('variety', 'of'): 19, ('to', 'prevent'): 19, ('on', 'december'): 19, ('involved', 'in'): 19, ('is', 'now'): 19, ('have', 'a'): 19, ('known', 'for'): 19, ('for', 'example'): 19, ('the', '9th'): 19, ('war', 'and'): 19, ('group', 'of'): 19, ('not', 'be'): 19, ('of', '1'): 19, ('above', 'the'): 19, ('and', 'three'): 19, ('served', 'as'): 19, ('on', '1'): 19, ('and', 'they'): 19, ('he', 'did'): 19, ('the', 'southern'): 19, ('a', 'major'): 19, ('built', 'in'): 19, ('naktong', 'river'): 19, ('river', 'and'): 19, ('set', 'up'): 19, ('were', 'in'): 19, ('it', 'had'): 19, ('back', 'of'): 19, ('hed', 'pe'): 19, ('the', 'presence'): 19, ('presence', 'of'): 19, ('using', 'the'): 19, ('the', 'u'): 19, ('was', 'first'): 19, ('award', 'for'): 19, ('felt', 'that'): 19, ('is', 'one'): 19, ('the', 'heads'): 19, ('number', 'one'): 19, ('the', 'eastern'): 19, ('big', 'show'): 19, ('light', 'tank'): 19, ('head', 'coach'): 19, ('that', 'nero'): 19, ('the', 'route'): 19, ('austro', 'hungarian'): 19, ('his', 'life'): 18, ('range', 'of'): 18, ('is', 'that'): 18, ('shortly', 'after'): 18, ('because', 'it'): 18, ('it', 'would'): 18, ('or', 'the'): 18, ('the', 'imperial'): 18, ('had', 'previously'): 18, ('only', 'a'): 18, ('took', 'place'): 18, ('the', 'development'): 18, ('the', 'track'): 18, ('and', 'has'): 18, ('the', 'music'): 18, ('in', 'new'): 18, ('the', 'billboard'): 18, ('of', 'fire'): 18, ('the', 'remaining'): 18, ('the', 'upper'): 18, ('at', 'this'): 18, ('but', 'it'): 18, ('top', 'of'): 18, ('the', 'port'): 18, ('to', 'create'): 18, ('was', 'formed'): 18, ('was', 'an'): 18, ('miles', 'per'): 18, ('heavy', 'rainfall'): 18, ('the', 'old'): 18, ('the', 'men'): 18, ('the', 'month'): 18, ('it', 'in'): 18, ('at', 'no'): 18, ('no', '20'): 18, ('the', 'official'): 18, ('the', 'spanish'): 18, ('published', 'in'): 18, ('of', 'temnospondyls'): 18, ('the', 'mouth'): 18, ('was', 'later'): 18, ('center', 'of'): 18, ('kershaw', 'was'): 18, ('the', 'dodgers'): 18, ('s', 'first'): 18, ('sent', 'to'): 18, ('to', 'leave'): 18, ('at', 'ufc'): 18, ('the', 'museo'): 18, ('stevens', 'was'): 18, ('the', 'crater'): 18, ('war', 'graves'): 18, ('ub', 'i'): 18, ('nerva', 's'): 18, ('written', 'by'): 17, ('production', 'of'): 17, ('the', 'chinese'): 17, ('of', 'du'): 17, ('s', 'work'): 17, ('attempt', 'to'): 17, ('during', 'this'): 17, ('was', 'appointed'): 17, ('a', 'long'): 17, ('that', 'his'): 17, ('to', 'use'): 17, ('the', 'beginning'): 17, ('as', 'its'): 17, ('and', 'as'): 17, ('used', 'in'): 17, ('a', 'significant'): 17, ('way', 'to'): 17, ('in', 'front'): 17, ('the', 'ijn'): 17, ('the', 'design'): 17, ('as', 'they'): 17, ('led', 'the'): 17, ('but', 'they'): 17, ('of', 'her'): 17, ('support', 'of'): 17, ('in', 'october'): 17, ('the', 'morning'): 17, ('referred', 'to'): 17, ('northeast', 'of'): 17, ('utc', 'on'): 17, ('the', 'northwest'): 17, ('infantry', 'regiment'): 17, ('the', 'tanks'): 17, ('the', 'hill'): 17, ('a', '2'): 17, ('the', 'situation'): 17, ('no', 'longer'): 17, ('made', 'the'): 17, ('released', 'on'): 17, ('found', 'to'): 17, ('in', 'february'): 17, ('similar', 'to'): 17, ('age', 'of'): 17, ('does', 'not'): 17, ('version', 'of'): 17, ('the', '2010'): 17, ('coast', 'of'): 17, ('announced', 'that'): 17, ('arjona', 's'): 17, ('the', 'undertaker'): 17, ('that', 'lesnar'): 17, ('he', 'felt'): 17, ('20', 'squadron'): 17, ('ft', 'wide'): 17, ('the', 'manila'): 17, ('road', 'cr'): 17, ('television', 'series'): 16, ('in', '2006'): 16, ('make', 'the'): 16, ('this', 'period'): 16, ('time', 'and'): 16, ('the', 'emperor'): 16, ('in', 'december'): 16, ('later', 'the'): 16, ('period', 'of'): 16, ('the', 'death'): 16, ('instead', 'of'): 16, ('not', 'to'): 16, ('when', 'they'): 16, ('his', 'wife'): 16, ('used', 'the'): 16, ('his', 'death'): 16, ('their', 'own'): 16, ('in', 'some'): 16, ('the', 'single'): 16, ('should', 'be'): 16, ('the', 'pacific'): 16, ('invasion', 'of'): 16, ('the', 'ship'): 16, ('a', 'high'): 16, ('was', 'considered'): 16, ('consisted', 'of'): 16, ('of', 'two'): 16, ('to', 'hold'): 16, ('and', 'more'): 16, ('in', 'august'): 16, ('the', 'history'): 16, ('a', 'great'): 16, ('million', 'in'): 16, ('the', 'majority'): 16, ('majority', 'of'): 16, ('the', 'island'): 16, ('naktong', 'bulge'): 16, ('september', '1'): 16, ('located', 'at'): 16, ('where', 'it'): 16, ('to', 'reach'): 16, ('the', 'previous'): 16, ('he', 'and'): 16, ('the', 'village'): 16, ('on', 'their'): 16, ('of', 'being'): 16, ('designed', 'by'): 16, ('temnospondyls', 'were'): 16, ('north', 'america'): 16, ('also', 'a'): 16, ('sustained', 'winds'): 16, ('went', 'on'): 16, ('he', 'made'): 16, ('a', 'game'): 16, ('control', 'of'): 16, ('second', 'world'): 16, ('the', 'operation'): 16, ('gazan', 's'): 16, ('triple', 'h'): 16, ('the', 'story'): 16, ('ft', 'high'): 16, ('headdress', 'is'): 16, ('ft', 'deep'): 16, ('northern', 'ireland'): 16, ('bintulu', 'is'): 16, ('sdn', 'bhd'): 16, ('the', 'hustler'): 16, ('the', 'television'): 15, ('in', 'two'): 15, ('in', '2008'): 15, ('his', 'father'): 15, ('death', 'of'): 15, ('was', 'one'): 15, ('the', 'three'): 15, ('the', 'government'): 15, ('the', 'earliest'): 15, ('wrote', 'that'): 15, ('same', 'time'): 15, ('the', 'people'): 15, ('seen', 'in'): 15, ('the', 'highest'): 15, ('group', 's'): 15, ('on', 'both'): 15, ('pair', 'of'): 15, ('a', 'further'): 15, ('laid', 'down'): 15, ('down', 'in'): 15, ('the', 'lower'): 15, ('a', 'special'): 15, ('both', 'sides'): 15, ('the', 'gun'): 15, ('at', 'an'): 15, ('8', 'in'): 15, ('was', 'built'): 15, ('the', 'light'): 15, ('to', 'bring'): 15, ('task', 'force'): 15, ('the', 'attack'): 15, ('two', 'days'): 15, ('for', 'several'): 15, ('had', 'no'): 15, ('in', 'damage'): 15, ('the', 'un'): 15, ('was', 'unable'): 15, ('time', 'in'): 15, ('night', 'of'): 15, ('was', 'still'): 15, ('road', 'and'): 15, ('23rd', 'infantry'): 15, ('the', 'battalion'): 15, ('he', 'could'): 15, ('once', 'again'): 15, ('album', 'was'): 15, ('been', 'found'): 15, ('into', 'an'): 15, ('tried', 'to'): 15, ('if', 'the'): 15, ('needed', 'to'): 15, ('the', 'age'): 15, ('out', 'to'): 15, ('up', 'in'): 15, ('the', 'site'): 15, ('modern', 'amphibians'): 15, ('the', 'oldest'): 15, ('a', 'member'): 15, ('a', 'three'): 15, ('was', 'announced'): 15, ('in', '2011'): 15, ('his', 'mother'): 15, ('the', 'san'): 15, ('up', 'his'): 15, ('the', 'series'): 15, ('become', 'the'): 15, ('who', 'were'): 15, ('if', 'he'): 15, ('latin', 'pop'): 15, ('in', 'japan'): 15, ('monsoon', 'trough'): 15, ('the', 'austro'): 15, ('is', 'in'): 15, ('part', 'in'): 15, ('royal', 'rumble'): 15, ('at', 'wrestlemania'): 15, ('lesnar', 'defeated'): 15, ('great', 'intelligence'): 15, ('metres', '4'): 15, ('decorated', 'with'): 15, ('lorenzo', 'colossal'): 15, ('film', 'was'): 15, ('cassius', 'dio'): 15, ('in', 'manila'): 15, ('boats', 'were'): 15, ('a', 'two'): 14, ('by', 'an'): 14, ('a', 'successful'): 14, ('of', 'what'): 14, ('was', 'born'): 14, ('had', 'an'): 14, ('in', 'that'): 14, ('him', 'a'): 14, ('only', 'one'): 14, ('he', 'wrote'): 14, ('left', 'the'): 14, ('remained', 'in'): 14, ('in', 'her'): 14, ('place', 'in'): 14, ('20th', 'century'): 14, ('do', 'not'): 14, ('and', 'some'): 14, ('and', 'also'): 14, ('was', 'able'): 14, ('a', 'variety'): 14, ('one', 'direction'): 14, ('a', 'group'): 14, ('from', 'its'): 14, ('during', 'world'): 14, ('the', 'loss'): 14, ('loss', 'of'): 14, ('participated', 'in'): 14, ('where', 'they'): 14, ('the', 'invasion'): 14, ('enough', 'to'): 14, ('to', 'that'): 14, ('the', 'construction'): 14, ('line', 'of'): 14, ('it', 'also'): 14, ('decided', 'that'): 14, ('considered', 'a'): 14, ('added', 'to'): 14, ('the', 'high'): 14, ('the', 'mid'): 14, ('were', 'built'): 14, ('one', 'on'): 14, ('of', 'four'): 14, ('assigned', 'to'): 14, ('state', 'of'): 14, ('its', 'first'): 14, ('be

Costruisci una tabella con le seguenti colonne: parola successiva $v_2$, parola precedente $v_1$ e la probabilità condizionata di $v_2$ nota la parola precedente $v_1$.

In [ ]:
righe = []

for (w1, w2), count in frequenze_bigrammi.items():
    freq_w1 = frequenze_type[w1]
    prob_w1 = freq_w1/l_corpus
    prob_w1_et_w2 = count / (l_corpus-1)
    righe.append([w1, w2, prob_w1_et_w2, prob_w1, count/freq_w1])

df_bigrammi = pd.DataFrame(
    righe,
    columns=[
        "w1",
        "w2",
        "P(w1_et_w2)",
        "P(w1)",
        "P(w2|w1)"
    ]
)

df_bigrammi.head()

        w1       w2  P(w1_et_w2)     P(w1)  P(w2|w1)
0   robert  boulter     0.000029  0.000097  0.300000
1  boulter   robert     0.000005  0.000116  0.041667
2  boulter       is     0.000005  0.000116  0.041667
3       is       an     0.000155  0.005507  0.028144
4       an  english     0.000010  0.003511  0.002759

### Predict
Genera la parola successiva in base alla probabilità condizionata.

In [49]:
def predictM1(parola, df_bigrammi):
    if parola not in df_bigrammi.w1.values:
        return df_parola.loc[df_parola["P(w1)"].idxmax()].w1

    # Trova la parola con probabilità massima
    df_parola = df_bigrammi[df_bigrammi.w1==parola]
    succ = df_parola.loc[df_parola["P(w2|w1)"].idxmax()].w2
    return succ

In [63]:
def predictM1(parola, df_bigrammi):
    # Se la parola non è nel dizionario, scegliamo una parola a caso basandoci sulle frequenze generali
    if parola not in df_bigrammi.w1.values:
        return np.random.choice(df_bigrammi.w1.values)

    df_possibili = df_bigrammi[df_bigrammi.w1 == parola]
    opzioni = df_possibili.w2.values
    probabilita = df_possibili["P(w2|w1)"].values
    succ = np.random.choice(opzioni, p=probabilita)

    return succ

In [66]:
print(predictM1("the", df_bigrammi))

teams

### L'autoregressione

Proviamo a generare un testo di n parole.

In [67]:
def genera_testo_markov1(parola_iniziale, n_parole, corpus):
    parola = parola_iniziale
    risultato = [parola]

    for _ in range(n_parole - 1):
        next_word = predictM1(parola, corpus)
        if next_word is None:
            break
        risultato.append(next_word)
        parola = next_word

    return " ".join(risultato)

In [68]:
print(genera_testo_markov1("swim", 12, df_bigrammi))

swim through may 12 55 he is neither discrimination nor the lrt

### Osservazioni

Cosa osservi? Il modello ha dimenticato l'inizio della frase?

Inserisci la tua risposta.

# Fonti

Linguistica computazionale, A. Lenci, S. Auriemma, M. Miliani, Hoeppli